"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./Providers";
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import { Flex } from "@chakra-ui/react";
import SideMenu from "@/component/SideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Flex flexDirection={"row"}>
            <SideMenu />
            <Flex w={"100%"} flexDirection={"column"}>
              <Header />
              {children}
              <Footer />
            </Flex>
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
